### ISSUE TITLE
Change WireRenderFile to $files->render

### ISSUE THREAD

**Issue by ivangretsky** [NinjasCL/wire-render-pattern#3]
It is the right way to do now [looking in the code](https://github.com/processwire/processwire/blob/master/wire/core/Functions.php#L487).

**Comment by clsource** [comment]
thanks, 
I will put a comment in the docs mention it.
Since both methods will work fine.
It just a matter of taste :)

**Comment by ivangretsky** [comment]
I have a feeling that this is not just a matter of taste and there could be contexts in which the API variable will work and the function will not. Like in RepeaterMatrix field templates, for example. Can't be 100% sure though.

**Comment by clsource** [comment]
I think is going to work well in Processwire 3.x
since have namespaces. You can call the function like
`\Processwire\wireRenderFile()` if you are in a different context.

But maybe in 2.8 will have some troubles if you are in a different context, 
and maybe its better to use `wire('files')->render()` function.
